stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - ./gradlew build

unit test:
    stage: test
    script:
        - ./gradlew test
        
sonar test:
    stage: test
    script:
        - ./gradlew sonarqube

deploy:
    stage: deploy
    script:
        - docker image build -t premseats .
